build: allign mypy cfg and ver to core
wuwentao/midea_ac_lan pull request #106
Opened 2024-06-20 13:40 UTC by chemelli74

# PR Description

## Reason & Detail

## Related issue

fix #X

2024-06-20 23:57 UTC, Necroneco requested changes

2024-06-20 23:57 UTC, Necroneco commented on custom_components/midea_ac_lan/config_flow.py
> +                        f"Can not get midea cloud: {
Python version 3.11 does not allow new lines in expression parts of non-triple-quoted f-strings

2024-06-21 07:45 UTC, Necroneco commented on custom_components/midea_ac_lan/config_flow.py
> +                        f"Can not get midea cloud: {
Do this in later PR

2024-06-21 07:45 UTC, Necroneco approved these changes

2024-06-21 08:06 UTC, Necroneco submitted a review, later dismissed

2024-06-21 08:06 UTC, Necroneco commented on custom_components/midea_ac_lan/config_flow.py
> +                            device.get(CONF_TYPE))})"
another need fmt: off

2024-06-21 08:10 UTC, chemelli74 commented on custom_components/midea_ac_lan/config_flow.py
> +                            device.get(CONF_TYPE))})"
Done

2024-06-21 08:10 UTC, Necroneco approved these changes

2024-06-21 08:13 UTC, merged