feat: add install script
wuwentao/midea_ac_lan pull request #204
Opened 2024-07-04 14:48 UTC by wuwentao

# PR Description
add bash script to install midea_ac_lan

## Reason & Detail

## Related issue

fix #X

2024-07-04 14:51 UTC, chemelli74 commented on scripts/install.sh
> +# wget -q -O - https://raw.githubusercontent.com/wuwentao/midea_ac_lan/master/scripts/install.sh | ARCHIVE_TAG=v0.4.2 bash -
I would first download `manifest.json` and then take the version from there to avoid more maintenance.

2024-07-04 17:09 UTC, rokam approved these changes
Looks good to me. Although I don't like to use install scripts.

2024-07-04 17:16 UTC, chemelli74 requested changes
I would like to avoid the hardcoded version

2024-07-05 04:24 UTC, wuwentao commented
@chemelli74  what's the hardcode version info? could you help to confirm ?

there is only a command example with version tag for help, it can be used for version rollback.

2024-07-05 07:16 UTC, chemelli74 commented
> @chemelli74 what's the hardcode version info? could you help to confirm ?
> 
> there is only a command example with version tag for help, it can be used for version rollback.

Sorry misread from mobile.
Please add a clear info on top is an example.

2024-07-05 10:02 UTC, merged