feat: reset device add config flow
wuwentao/midea_ac_lan pull request #206
Opened 2024-07-05 16:41 UTC by wuwentao

# PR Description
1.  cache login data
2. add remove cached login data step
3.  add a simple skip login option
4.  add async def check_cloud_login and check_cloud_key
5. reset add device step
6. disable v3 device add with v2/v1 protocol
7. force check device_id/device_protocol in finally step
8. to be done, can be review via comments part

## Reason & Detail

## Related issue

fix #X

2024-07-08 18:00 UTC, chemelli74 requested changes
Sorry to request changes, but I'm not a fan of a single PR with so many changes.

2024-07-08 18:06 UTC, chemelli74 requested changes

2024-07-08 18:06 UTC, chemelli74 commented on .pre-commit-config.yaml
> +        args: ["--rcfile=pylintrc", "-v"]
If this change is needed, please do it on a separate PR

2024-07-09 03:28 UTC, wuwentao commented
> Sorry to request changes, but I'm not a fan of a single PR with so many changes.

thanks, it's a fullly of the old feature, not one feature, all the old process has been droped, and  most of the feature bounds in this new process.
and every step has add with all the detail comments and why we do it now, old process without any comments and info why it to do that...
if there is any error, just refer to the comments, please fullly drop old mode and old codes.

we don't have any testcase in integration side, most of the current process only can be test by manual action, and I have manual tested/verified with 90% of current code changes, confirmed it works as expected flow.

if we want to split it with more PRs, we should  consider how to deploy it step by step..... each feature should combind one by one, also conside how to replace the old code step by step.

wish you have any good solution to deloy it step by step with old proces replace, and I don't want to waste time with old process.... so I just select a fresh new one.
could you help me to finish it with more PRs?  I can drop my current PR, sorry....
waitting for your feedback with the solution when we got a agreement.
there is too many auth failed github issue, we should release a new version to check and confirm it.

2024-07-09 08:21 UTC, rokam commented on .pre-commit-config.yaml
> +        args: ["--rcfile=pylintrc", "-v"]
```suggestion
```

2024-07-09 08:30 UTC, rokam approved these changes

2024-07-09 08:32 UTC, merged