fix dev container
wuwentao/midea_ac_lan pull request #375
Opened 2024-10-27 15:40 UTC by constambeys

fix dev container fails

1 package is looking for funding
  run `npm fund` for details
./scripts/setup.sh: line 13: cd: ./scripts/..: No such file or directory

2024-10-27 17:17 UTC, chemelli74 requested changes
Hi @constambeys and thx for contributing!

In order to install the plugin outside the git folder, we need to change directory.
Current container works fine for me on several different projects.
We need to investigate what's wrong on your scenario.

2024-10-27 19:06 UTC, constambeys commented
I am new to this project but I am interested in how it works !

Dev container does not build, The directory is already changed in line 5 to the root why changing again !

2024-10-27 20:49 UTC, chemelli74 commented
> Dev container does not build, The directory is already changed in line 5 to the root why changing again !

Because you need to install in different path the different components.

Back to your issue:

1. What's is not working exactly ?
2. How are you creating/starting the `devcontainer` ?
3. Which is the docker version you are running ?
4. Is the host Windows or Linux ?

2024-10-28 09:00 UTC, constambeys commented
![Screenshot from 2024-10-28 10-19-23](https://github.com/user-attachments/assets/0eaf726c-96c1-43a6-9324-04a49fc44268)
1.     See attachment !
2.     Reopen folder in container
3.     Docker Engine v27.2.0
4.     Tried on both Fedora Linux and Windows 11

2024-11-02 14:45 UTC, constambeys commented
Still the same !!! 

Maybe you should add some debug messages to understand what is going on !

2024-11-05 10:55 UTC, wuwentao commented
the screenshot should not the root cause, and the error should be exist before this screenshot.
we need to find out the **first** error step, and it may not report error or exit 1, so the jobs continue running, and you got this error at the end of the scripts.

you can check the error before it, there is detail log for devcontainer build job, vscode will print all.
if you still can't fix it, maybe you can upload devcontainer log as a file.

2024-11-05 15:42 UTC, wuwentao commented
I have test with my windows PC with WSL2,  try to run dev container jobs: **[Rebuild devcontainer without cache]**, and got the same error.

```
Running the postCreateCommand from devcontainer.json...

[379457 ms] Start: Run in container: /bin/sh -c scripts/setup.sh
pre-commit installed at .git/hooks/pre-commit
pre-commit installed at .git/hooks/commit-msg
```
it start to run this script , and got an error with it:
```
[389501 ms] [15:28:52] Error while preparing to install dependencies and extension packs of the extension: ryanluker.vscode-coverage-gutters
[389503 ms] [15:28:52] Error while installing extensions: 40482AC94B7F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:622:

[389504 ms] [15:28:52] Failed: 40482AC94B7F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:622:
```
so, the result is :
```
added 11 packages in 46s

1 package is looking for funding
  run `npm fund` for details
scripts/setup.sh: line 13: cd: scripts/..: No such file or directory
```

2024-11-05 15:43 UTC, wuwentao commented
a ttach the full log as below:
[devcontainer.log](https://github.com/user-attachments/files/17635065/devcontainer.log)

2025-06-06 01:39 UTC, merged